/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as ClassementsRouteImport } from './routes/classements'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ReglementRouteImport } from './routes/reglement'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as AdminTestsRouteImport } from './routes/admin.tests'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as BoutiqueProductIdRouteImport } from './routes/boutique.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementsRoute = ClassementsRouteImport.update({
  id: '/classements',
  path: '/classements',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglementRoute = ReglementRouteImport.update({
  id: '/reglement',
  path: '/reglement',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoutiqueRoute,
} as any)
const BoutiqueProductIdRoute = BoutiqueProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => BoutiqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/classements': typeof ClassementsRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/panier': typeof PanierRoute
  '/reglement': typeof ReglementRoute
  '/vote': typeof VoteRoute
  '/admin/tests': typeof AdminTestsRoute
  '/boutique/$productId': typeof BoutiqueProductIdRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classements': typeof ClassementsRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/panier': typeof PanierRoute
  '/reglement': typeof ReglementRoute
  '/vote': typeof VoteRoute
  '/admin/tests': typeof AdminTestsRoute
  '/boutique/$productId': typeof BoutiqueProductIdRoute
  '/boutique': typeof BoutiqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/classements': typeof ClassementsRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/panier': typeof PanierRoute
  '/reglement': typeof ReglementRoute
  '/vote': typeof VoteRoute
  '/admin/tests': typeof AdminTestsRoute
  '/boutique/$productId': typeof BoutiqueProductIdRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/classements'
    | '/commande'
    | '/compte'
    | '/panier'
    | '/reglement'
    | '/vote'
    | '/admin/tests'
    | '/boutique/$productId'
    | '/boutique/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classements'
    | '/commande'
    | '/compte'
    | '/panier'
    | '/reglement'
    | '/vote'
    | '/admin/tests'
    | '/boutique/$productId'
    | '/boutique'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/classements'
    | '/commande'
    | '/compte'
    | '/panier'
    | '/reglement'
    | '/vote'
    | '/admin/tests'
    | '/boutique/$productId'
    | '/boutique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRouteWithChildren
  ClassementsRoute: typeof ClassementsRoute
  CommandeRoute: typeof CommandeRoute
  CompteRoute: typeof CompteRoute
  PanierRoute: typeof PanierRoute
  ReglementRoute: typeof ReglementRoute
  VoteRoute: typeof VoteRoute
  AdminTestsRoute: typeof AdminTestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classements': {
      id: '/classements'
      path: '/classements'
      fullPath: '/classements'
      preLoaderRoute: typeof ClassementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglement': {
      id: '/reglement'
      path: '/reglement'
      fullPath: '/reglement'
      preLoaderRoute: typeof ReglementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof BoutiqueRoute
    }
    '/boutique/$productId': {
      id: '/boutique/$productId'
      path: '/$productId'
      fullPath: '/boutique/$productId'
      preLoaderRoute: typeof BoutiqueProductIdRouteImport
      parentRoute: typeof BoutiqueRoute
    }
  }
}

interface BoutiqueRouteChildren {
  BoutiqueProductIdRoute: typeof BoutiqueProductIdRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
}

const BoutiqueRouteChildren: BoutiqueRouteChildren = {
  BoutiqueProductIdRoute: BoutiqueProductIdRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
}

const BoutiqueRouteWithChildren = BoutiqueRoute._addFileChildren(
  BoutiqueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRouteWithChildren,
  ClassementsRoute: ClassementsRoute,
  CommandeRoute: CommandeRoute,
  CompteRoute: CompteRoute,
  PanierRoute: PanierRoute,
  ReglementRoute: ReglementRoute,
  VoteRoute: VoteRoute,
  AdminTestsRoute: AdminTestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
